services:
  shorts_forward:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorts_forward
    restart: always
    environment:
      - env=prod
      - APP_TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - APP_DOMEN=${DOMEN}
    ports:
      - 992:992
    volumes:
      - ./assets:/assets:ro