services:
  shorts_forward:
    image: ghcr.io/stounhandj/shorts_forward:latest
    container_name: shorts_forward
    restart: always
    environment:
      - env=prod
      - APP_TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - APP_DOMEN=${DOMEN}
    ports:
      - 80:992
    volumes:
      - ./assets:/assets:ro